fail_fast: false
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: fix-byte-order-marker
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: check-toml
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: cargo-fmt
        name: cargo fmt
        description: Format files with rustfmt.
        entry: bash -c 'cargo fmt -- --check'
        language: rust
      - id: cargo-clippy
        name: cargo clippy
        description: Run clippy on the codebase.
        entry: bash -c 'cargo clippy -- -D warnings'
        language: rust
      - id: conventional-commit-msg-validation
        name: commit message conventional validation
        language: pygrep
        entry: '^(breaking|build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test|squash|fixup){1}(\([\w\-\.]+\))?(!)?: ([\w `])+([\s\S]*)'
        args: [--multiline, --negate]
        stages: [commit-msg]
      - id: cargo-sort
        name: Check Cargo.toml is sorted
        description: Ensure Cargo.toml is sorted
        entry: bash -c 'cargo sort --workspace'
        language: rust
        files: Cargo\.toml
        pass_filenames: false
