[package]
name = "kernel"
version = "0.1.0"
edition = "2024"

default-run = "kernel"

[dependencies]
sbi-rt = "0.0.3"
log = "0.4.27"
buddy_system_allocator = "0.11.0"
riscv = { git = "https://github.com/rcore-os/riscv", features = [
    "inline-asm",
] } # TODO: use other riscv in crates.io
lazy_static = { version = "1.5.0", features = ["spin_no_std"] }

[dev-dependencies]
user_lib = { path = "../user_lib" }
